---
- name: Install Java 11
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - java-11-openjdk

- name: Save java home folder
  shell: "dirname $(dirname $(rpm -ql java-11-openjdk-headless | grep '/bin/java$'))"
  register: java_dir
  changed_when: false

- name: Check Java on target system (1)
  stat:
    path: "{{ java_dir.stdout }}/bin/java"
  register: java_dir_java

- name: Check Java on target system (2)
  fail:
    msg: Check Java package installation. Unable to find executable at {{ java_dir.stdout }}/bin/java.
  when: not java_dir_java.stat.exists
