---
# This script performs different parameters validation

######################################
# Nexus-specific parameters validation
######################################

# Check port-type parameter: nexus_port
- name: Check port-type parameters
  fail:
    msg: "Parameter {{ item.name }} has value {{ item.value }}, which is not a valid TCP/IP port number !"
  when: not ( item.value | string | regex_search( '[0-9]*' ) ) or ( item.value | int < 0 ) or ( item.value | int > 65535 )
  with_items:
    - { name: "nexus_port", value: "{{ nexus_port }}" }
