---

# This script used to update current application parameters if the application is already installed
# It can be run just after the installation or after some time (re-configuration)
# Some parameters cannot be re-configured (installation path, user, group, systemd status)
# All other parameters must be reconfigured here

# Input params:
#   - install_prefix - (defined in group_vars/all) - gives the location config file: {{install_prefix}}/nexus/sonatype-work/nexus3/etc/nexus.properties
#

- name: Update host
  replace:
    path: "{{ install_prefix }}/nexus/sonatype-work/nexus3/etc/nexus.properties"
    regexp:  '^(#)?(\s)*application-host=.*'
    replace: 'application-host={{ nexus_host }}'
  when: nexus_host != "0.0.0.0"

- name: Update host (2)
  replace:
    path: "{{ install_prefix }}/nexus/sonatype-work/nexus3/etc/nexus.properties"
    regexp:  '^(#)?(\s)*application-host=.*'
    replace: '# application-host={{ nexus_host }}'
  when: nexus_host == "0.0.0.0"

- name: Update port
  replace:
    path: "{{ install_prefix }}/nexus/sonatype-work/nexus3/etc/nexus.properties"
    regexp:  '^(#)?(\s)*application-port=.*'
    replace: 'application-port={{ nexus_port }}'
  when: nexus_port != "8081"

- name: Update port (2)
  replace:
    path: "{{ install_prefix }}/nexus/sonatype-work/nexus3/etc/nexus.properties"
    regexp:  '^(#)?(\s)*application-port=.*'
    replace: '# application-port={{ nexus_port }}'
  when: nexus_port == "8081"
