---

# Validate parameters
- import_tasks: params_validation.yml

# Check situation with current status (e.g. installed but into different path - that would be an error)
- include_tasks: check_status.yml

# Stopping services (if they exist) before making any changes in the configuration
- include_tasks: ../../common/tasks/stop_service.yml
  with_items:
    - "talend-kafka"
    - "talend-zookeeper"
  loop_control:
    loop_var: app_service


# We will include installation with yum or with rpm depending of prefix used
- include_tasks: install_yum.yml
  when: install_prefix == '/opt/talend'

- include_tasks: install_rpm.yml
  when: install_prefix != '/opt/talend'


# Updating configuration for Zookeeper and Kafka
- import_tasks: update_config.yml

# Set up Zookeeper ACL - pre-start tasks
- include_tasks: update_acl.yml
  when: zook_setacl == 'yes' and app_install_systemd == 'yes'

# Starting services (if they are exist)
- include_tasks: ../../common/tasks/start_service.yml
  with_items:
    - "talend-zookeeper"
    - "talend-kafka"
  loop_control:
    loop_var: app_service

# Set up Zookeeper ACL - post-start tasks
- include_tasks: update_acl2.yml
  when: zook_setacl == 'yes' and app_install_systemd == 'yes'
