---
# This script performs different parameters validation

######################################
# Kafka-specific parameters validation
######################################

# Check folder-type parameters: zook_datadir, kafka_log_dirs
- include_tasks: ../../common/tasks/params_validation_dir.yml
  with_items:
    - "{{ zook_datadir }}"
    - "{{ kafka_log_dirs }}"
  loop_control:
    loop_var: app_dir

# Check port-type parameter: zook_clientPort
- name: Check port-type parameters
  fail:
    msg: "Parameter {{ item.name }} has value {{ item.value }}, which is not a valid TCP/IP port number !"
  when: not ( item.value | string | regex_search( '[0-9]*' ) ) or ( item.value | int < 0 ) or ( item.value | int > 65535 )
  with_items:
    - { name: "zook_clientPort", value: "{{ zook_clientPort }}" }

# Check integer params which can be set to 0: zook_macClientCnxns, kafka_broker_id, kafka_group_initial_rebalance_delay_ms
- name: Check generic integer equal or above zero
  fail:
    msg: "Parameter {{ item.name }} has value {{ item.value }}, which is not a valid integer number !"
  when: not ( item.value | string | regex_search( '[0-9]*' ) )
  with_items:
    - { name: "zook_macClientCnxns",                    value: "{{ zook_macClientCnxns }}" }
    - { name: "kafka_broker_id",                        value: "{{ kafka_broker_id }}" }
    - { name: "kafka_group_initial_rebalance_delay_ms", value: "{{ kafka_group_initial_rebalance_delay_ms }}" }

# Check for positive integers (>0): kafka_num_network_threads, kafka_num_io_threads, kafka_num_partitions,
#     kafka_num_recovery_threads_per_data_dir, kafka_offsets_topic_replication_factor, kafka_transaction_state_log_replication_factor,
#     kafka_transaction_state_log_min_isr, kafka_log_flush_interval_messages, kafka_log_flush_interval_ms,
#     kafka_log_retention_hours, kafka_log_retention_check_interval_ms, kafka_zookeeper_connection_timeout_ms
- name: Check positive integer parameter above zero
  fail:
    msg: "Parameter {{ item.name }} has value {{ item.value }}, which is not a valid positive integer number !"
  when: item.value | int < 1
  with_items:
    - { name: "kafka_num_network_threads",                      value: "{{ kafka_num_network_threads }}" }
    - { name: "kafka_num_io_threads",                           value: "{{ kafka_num_io_threads }}" }
    - { name: "kafka_num_partitions",                           value: "{{ kafka_num_partitions }}" }
    - { name: "kafka_num_recovery_threads_per_data_dir",        value: "{{ kafka_num_recovery_threads_per_data_dir }}" }
    - { name: "kafka_offsets_topic_replication_factor",         value: "{{ kafka_offsets_topic_replication_factor }}" }
    - { name: "kafka_transaction_state_log_replication_factor", value: "{{ kafka_transaction_state_log_replication_factor }}" }
    - { name: "kafka_transaction_state_log_min_isr",            value: "{{ kafka_transaction_state_log_min_isr }}" }
    - { name: "kafka_log_flush_interval_messages",              value: "{{ kafka_log_flush_interval_messages }}" }
    - { name: "kafka_log_flush_interval_ms",                    value: "{{ kafka_log_flush_interval_ms }}" }
    - { name: "kafka_log_retention_hours",                      value: "{{ kafka_log_retention_hours }}" }
    - { name: "kafka_log_retention_check_interval_ms",          value: "{{ kafka_log_retention_check_interval_ms }}" }
    - { name: "kafka_zookeeper_connection_timeout_ms",          value: "{{ kafka_zookeeper_connection_timeout_ms }}" }

# Check for ACL actions
- name: Check ZK ACL parameter
  fail:
    msg: Parameter zook_setacl can be only "yes" or "no"
  when: zook_setacl != "yes" and zook_setacl != "no"

- name: Check ACL and service startup conditions
  fail:
    msg: Parameter zook_setacl is set to "yes", but system services are not going to be installed, cannot proceed
  when: zook_setacl == "yes" and app_install_systemd == "no"

- name: Check ZK ACL compatibility
  fail:
    msg: Zookeeper ACL is supported only for Talend version 8.0 or above
  when: rpm_base_version < 8.0
