---

# This script used to update ZooKeeper ACL
# It requires ZooKeeper and Kafka services to be running
#
# This task should only be used if zook_setacl is set to "yes"
# This part of the configuration should be executed after ZooKeeper and Kafka servers are started up

# Check pre-conditions
- name: ZooKeeper ACL - check pre-conditions (1)
  fail:
    msg: Invalid import - task update_acl.yml must not be used if zook_setacl is not equal to "yes"
  when: zook_setacl != "yes"

- name: ZooKeeper ACL - check pre-conditions (2) - wait for ZooKeeper start-up
  wait_for:
    port: "{{ zook_clientPort }}"
    timeout: 30

- name: ZooKeeper ACL - check pre-conditions (3) - wait for Kafka start-up
  wait_for:
    port: "{{ kafka_listeners | urlsplit('port') }}"
    timeout: 30

- name: ZooKeeper - activating ACL mechanism
  command:
    cmd: "{{ install_prefix }}/kafka/bin/zookeeper-security-migration.sh --zookeeper.acl=secure"
    creates: "{{ install_prefix }}/kafka/config/talend.acl"
  environment:
    JAVA_HOME: "{{ java_dir.stdout }}"
    KAFKA_HOME: "{{ install_prefix }}/kafka"
    KAFKA_OPTS: "-Djava.security.auth.login.config={{ install_prefix }}/kafka/config/jaas_config.conf"

- name: ZooKeeper ACL - setting up individual nodes security
  command:
    cmd: "{{ install_prefix }}/kafka/bin/zookeeper-shell.sh localhost:{{ zook_clientPort }} setAcl {{ zk_node }} sasl:admin:cdrwa,world:anyone:r"
    creates: "{{ install_prefix }}/kafka/config/talend.acl"
  environment:
    JAVA_HOME: "{{ java_dir.stdout }}"
    KAFKA_HOME: "{{ install_prefix }}/kafka"
    KAFKA_OPTS: "-Djava.security.auth.login.config={{ install_prefix }}/kafka/config/jaas_config.conf"
  with_items:
    - "/zookeeper"
    - "/zookeeper/quota"
    - "/consumers"
  loop_control:
    loop_var: zk_node

- name: Update config/talend.acl file
  lineinfile:
    path: "{{ install_prefix }}/kafka/config/talend.acl"
    line: "This file is used by Talend Ansible scripts. Do not remove!"
    state: present
    create: yes
    owner: "{{ install_user }}"
    group: "{{ install_group }}"
    mode: '0644'
