---

# This script used to update ZooKeeper ACL for the transition from ACL-enabled to ACL-disabled
# It requires ZooKeeper and Kafka services to be running
#
# This task should be used only if zook_setacl == "no" and file kafka/config/talend.acl exists

# Pre-conditions
- name: Check update_acl_pre - initial pre-conditions
  fail:
    msg: Invalid invocation for update_acl_pre.yml
  when: not ( zook_setacl == 'no' and app_install_systemd == 'yes' and var_jaas_file_stat.stat.exists )

# Check that ZooKeeper server is running in background

- name: ZooKeeper ACL - check pre-conditions for de-activation - ensure that ZooKeeper is running
  wait_for:
    port: "{{ zook_clientPort }}"
    timeout: 30

- name: ZooKeeper ACL - deconfiguring individual nodes security
  command:
    cmd: "{{ install_prefix }}/kafka/bin/zookeeper-shell.sh localhost:{{ zook_clientPort }} setAcl {{ zk_node }} world:anyone:cdrwa"
  environment:
    JAVA_HOME: "{{ java_dir.stdout }}"
    KAFKA_HOME: "{{ install_prefix }}/kafka"
    KAFKA_OPTS: "-Djava.security.auth.login.config={{ install_prefix }}/kafka/config/jaas_config.conf"
  with_items:
    - "/zookeeper"
    - "/zookeeper/quota"
    - "/consumers"
  loop_control:
    loop_var: zk_node

- name: ZooKeeper - de-activating ACL mechanism
  command:
    cmd: "{{ install_prefix }}/kafka/bin/zookeeper-security-migration.sh --zookeeper.acl=unsecure"
  environment:
    JAVA_HOME: "{{ java_dir.stdout }}"
    KAFKA_HOME: "{{ install_prefix }}/kafka"
    KAFKA_OPTS: "-Djava.security.auth.login.config={{ install_prefix }}/kafka/config/jaas_config.conf"

- name: ZooKeeper - remove config/talend.acl file
  file:
    path: "{{ install_prefix }}/kafka/config/talend.acl"
    state: absent
