---
# This script performs different parameters validation

######################################
# MDM-specific parameter validation
######################################

- name: Show error about wrong value for parameter mdm_audit_log_enabled
  fail:
    msg: Wrong value for parameter "mdm_audit_log_enabled", must be 'yes' or 'no'
  when: mdm_audit_log_enabled != "no" and mdm_audit_log_enabled != "yes"

- name: Show error about wrong value for parameter mdm_database
  fail:
    msg: Wrong value for parameter "mdm_database", must be one of 'h2', 'mysql8', 'mysql', 'oracle', 'mssql', 'postgresql', 'db2'
  when: mdm_database != "h2" and mdm_database != "mysql8" and mdm_database != "mysql" and mdm_database != "oracle" and mdm_database != "mssql" and mdm_database != "postgresql" and mdm_database != "db2"

- name: Show error about wrong value for parameter mdm_db_driver
  fail:
    msg: Wrong value for parameter "mdm_db_driver", must be valid JAR when "mdm_database" is not 'h2'
  when: mdm_db_driver == "" and mdm_database != "h2"
