---
- name: Show error about wrong value for parameter tdp_server_port
  fail:
    msg: Wrong value for parameter "tdp_server_port", must be an integer
  when: tdp_server_port|int < 1

- name: Show error about wrong value for parameter tdp_server_port
  fail:
    msg: Wrong value for parameter "tdp_server_port", must be between 1 and 65535
  when: tdp_server_port|int <= 1 or tdp_server_port|int >= 65535

- name: Show error about wrong value for parameter tdp_server_compression_enabled
  fail:
    msg: Wrong value for parameter "tdp_server_compression_enabled", must be 'true' or 'false'
  when: tdp_server_compression_enabled != "true" and tdp_server_compression_enabled != "false"

- name: Show error about wrong value for parameter tdp_spring_mvc_async_request_timeout
  fail:
    msg: Wrong value for parameter "tdp_spring_mvc_async_request_timeout", must be an integer
  when: tdp_spring_mvc_async_request_timeout|int < 1

- name: Show error about wrong value for parameter tdp_mongodb_port
  fail:
    msg: Wrong value for parameter "tdp_mongodb_port", must be an integer
  when: tdp_mongodb_port|int < 1

- name: Show error about wrong value for parameter tdp_mongodb_port
  fail:
    msg: Wrong value for parameter "tdp_mongodb_port", must be between 1 and 65535
  when: tdp_mongodb_port|int <= 1 or tdp_mongodb_port|int >= 65535

- name: Show error about wrong value for parameter tdp_multi_tenancy_mongodb_active
  fail:
    msg: Wrong value for parameter "tdp_multi_tenancy_mongodb_active", must be 'true' or 'false'
  when: tdp_multi_tenancy_mongodb_active != "true" and tdp_multi_tenancy_mongodb_active != "false"

- name: Show error about wrong value for parameter tdp_security_token_renew_after
  fail:
    msg: Wrong value for parameter "tdp_security_token_renew_after", must be an integer
  when: tdp_security_token_renew_after|int < 1

- name: Show error about wrong value for parameter tdp_security_token_invalid_after
  fail:
    msg: Wrong value for parameter "tdp_security_token_invalid_after", must be an integer
  when: tdp_security_token_invalid_after|int < 1

- name: Show error about wrong value for parameter tdp_spring_http_multipart_maxFileSize
  fail:
    msg: Wrong value for parameter "tdp_spring_http_multipart_maxFileSize", must be an integer
  when: tdp_spring_http_multipart_maxFileSize|int < 1

- name: Show error about wrong value for parameter tdp_spring_http_multipart_maxRequestSize
  fail:
    msg: Wrong value for parameter "tdp_spring_http_multipart_maxRequestSize", must be an integer
  when: tdp_spring_http_multipart_maxRequestSize|int < 1

- name: Show error about wrong value for parameter tdp_dataset_records_limit
  fail:
    msg: Wrong value for parameter "tdp_dataset_records_limit", must be an integer
  when: tdp_dataset_records_limit|int < 1

- name: Show error about wrong value for parameter tdp_dataset_local_file_size_limit
  fail:
    msg: Wrong value for parameter "tdp_dataset_local_file_size_limit", must be an integer
  when: tdp_dataset_local_file_size_limit|int < 1

- name: Show error about wrong value for parameter tdp_dataset_list_limit
  fail:
    msg: Wrong value for parameter "tdp_dataset_list_limit", must be an integer
  when: tdp_dataset_list_limit|int < 1

- name: Show error about wrong value for parameter tdp_preparation_store_remove_hours
  fail:
    msg: Wrong value for parameter "tdp_preparation_store_remove_hours", must be an integer
  when: tdp_preparation_store_remove_hours|int < 1

- name: Show error about wrong value for parameter tdp_lock_preparation_delay
  fail:
    msg: Wrong value for parameter "tdp_lock_preparation_delay", must be an integer
  when: tdp_lock_preparation_delay|int < 1

- name: Show error about wrong value for parameter tdp_async_operation_concurrent_run
  fail:
    msg: Wrong value for parameter "tdp_async_operation_concurrent_run", must be an integer
  when: tdp_async_operation_concurrent_run|int < 1

- name: Show error about wrong value for parameter tdp_tcomp_SimpleFileIoDatastore_test_connection_visible
  fail:
    msg: Wrong value for parameter "tdp_tcomp_SimpleFileIoDatastore_test_connection_visible", must be 'true' or 'false'
  when: tdp_tcomp_SimpleFileIoDatastore_test_connection_visible != "true" and tdp_tcomp_SimpleFileIoDatastore_test_connection_visible != "false"

- name: Show error about wrong value for parameter tdp_dataquality_semantic_list_enable
  fail:
    msg: Wrong value for parameter "tdp_dataquality_semantic_list_enable", must be 'true' or 'false'
  when: tdp_dataquality_semantic_list_enable != "true" and tdp_dataquality_semantic_list_enable != "false"

- name: Show error about wrong value for parameter tdp_security_basic_enabled
  fail:
    msg: Wrong value for parameter "tdp_security_basic_enabled", must be 'true' or 'false'
  when: tdp_security_basic_enabled != "true" and tdp_security_basic_enabled != "false"

- name: Show error about wrong value for parameter tdp_security_oidc_client_claimIssueAtTolerance
  fail:
    msg: Wrong value for parameter "tdp_security_oidc_client_claimIssueAtTolerance", must be an integer
  when: tdp_security_oidc_client_claimIssueAtTolerance|int < 1

- name: Show error about wrong value for parameter tdp_security_oauth2_resource_filter_order
  fail:
    msg: Wrong value for parameter "tdp_security_oauth2_resource_filter_order", must be an integer
  when: tdp_security_oauth2_resource_filter_order|int < 1

- name: Show error about wrong value for parameter tdp_security_scim_enabled
  fail:
    msg: Wrong value for parameter "tdp_security_scim_enabled", must be 'true' or 'false'
  when: tdp_security_scim_enabled != "true" and tdp_security_scim_enabled != "false"

- name: Show error about wrong value for parameter tdp_security_oauth2_sso_login_use_forward
  fail:
    msg: Wrong value for parameter "tdp_security_oauth2_sso_login_use_forward", must be 'true' or 'false'
  when: tdp_security_oauth2_sso_login_use_forward != "true" and tdp_security_oauth2_sso_login_use_forward != "false"

- name: Show error about wrong value for parameter tdp_security_oauth2_resource_tokenInfoUriCache_enabled
  fail:
    msg: Wrong value for parameter "tdp_security_oauth2_resource_tokenInfoUriCache_enabled", must be 'true' or 'false'
  when: tdp_security_oauth2_resource_tokenInfoUriCache_enabled != "true" and tdp_security_oauth2_resource_tokenInfoUriCache_enabled != "false"

- name: Show error about wrong value for parameter tdp_tenant_account_cache_enabled
  fail:
    msg: Wrong value for parameter "tdp_tenant_account_cache_enabled", must be 'true' or 'false'
  when: tdp_tenant_account_cache_enabled != "true" and tdp_tenant_account_cache_enabled != "false"

- name: Show error about wrong value for parameter tdp_zuul_host_socket_timeout_millis
  fail:
    msg: Wrong value for parameter "tdp_zuul_host_socket_timeout_millis", must be an integer
  when: tdp_zuul_host_socket_timeout_millis|int < 1

- name: Show error about wrong value for parameter tdp_zuul_host_connect_timeout_millis
  fail:
    msg: Wrong value for parameter "tdp_zuul_host_connect_timeout_millis", must be an integer
  when: tdp_zuul_host_connect_timeout_millis|int < 1

- name: Show error about wrong value for parameter tdp_audit_log_enabled
  fail:
    msg: Wrong value for parameter "tdp_audit_log_enabled", must be 'true' or 'false'
  when: tdp_audit_log_enabled != "true" and tdp_audit_log_enabled != "false"

- name: Show error about wrong value for parameter tdp_appender_file_maxsize
  fail:
    msg: Wrong value for parameter "tdp_appender_file_maxsize", must be an integer
  when: tdp_appender_file_maxsize|int < 1

- name: Show error about wrong value for parameter tdp_appender_file_maxbackup
  fail:
    msg: Wrong value for parameter "tdp_appender_file_maxbackup", must be an integer
  when: tdp_appender_file_maxbackup|int < 1

- name: Show error about wrong value for parameter tdp_appender_http_async
  fail:
    msg: Wrong value for parameter "tdp_appender_http_async", must be 'true' or 'false'
  when: tdp_appender_http_async != "true" and tdp_appender_http_async != "false"

- name: Show error about wrong value for parameter tdp_hybrid_mode
  fail:
    msg: Wrong value for parameter "tdp_hybrid_mode", must be "yes" or "no"
  when: tdp_hybrid_mode != "yes" and tdp_hybrid_mode != "no"

- name: Show error about wrong value for parameter tdp_hybrid_mode (2)
  fail:
    msg: Wrong value for parameter "tdp_hybrid_mode", it can be set to "yes" only for version 7.3 and above
  when: tdp_hybrid_mode == "yes" and rpm_base_version < 7.3

- name: Show error about wrong value for parameter tdp_hybrid_region
  fail:
    msg: Wrong value for parameter "tdp_hybrid_region", must be one of "us", "eu", "ap", "au", "us-west" or "at"
  when: tdp_hybrid_region != "us" and tdp_hybrid_region != "eu" and tdp_hybrid_region != "ap" and tdp_hybrid_region != "au" and tdp_hybrid_region != "at" and tdp_hybrid_region != "us-west"

- name: Check correct MinIO port (if MinIO is used)
  fail:
    msg: Incorrect value tdp_s3endpoint, port does not match with variable minio_port
  when: minio_port is defined and tdp_s3endpoint | urlsplit('port') != minio_port | int

- name: Check correct language setting
  fail:
    msg: tdp_language can be one of en-US, fr-FR, jp-JP or zh-CN
  when: tdp_language != 'en-US' and tdp_language != 'fr-FR' and tdp_language != 'jp-JP' and tdp_language != 'zh-CN'

- name: Check correct value for tdp_app_products
  fail:
    msg: tdp_app_products can be only one of "yes" or "no"
  when: tdp_app_products != "yes" and tdp_app_products != "no"
